version: '3.8'

services:
  graphdb:
    image: ontotext/graphdb:10.8.1 # Replace with the desired GraphDB version
    container_name: graphdb-instance
    ports:
      - "7200:7200" # GraphDB web interface
