version: '3.8'
services:
  rest-service:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=http://localhost:7200/repositories/MoviesRepo
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.4'
        reservations:
          memory: 128M
          cpus: '0.2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      interval: 5s
      timeout: 2s
      retries: 3

  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./RedisCache
