version: '3.8'

services:
  rest-service:
    build:
      context: .  # "." refers to the current directory (RestService)
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=http://graphdb-instance:7200/repositories/MoviesRepo
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '0.6'
        reservations:
          memory: 2G
          cpus: '0.9'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - shared-network

  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - shared-network

volumes:
  cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./RedisCache

networks:
  shared-network:
    external: true
